# Generated by Django 5.2.17 on 2026-09-29 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseApp', '0001_initial'),
        ('ExpeditionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprises', to='EntrepriseApp.entreprise'),
        ),
    ]
