# Generated by Django 5.2.17 on 2026-09-29 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntrepriseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('type_vehicule', models.CharField(choices=[('camion', 'Camion'), ('voiture', 'Voiture'), ('moto', 'Moto')], max_length=50)),
                ('capacite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilite', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('en_service', 'En service'), ('hors_service', 'Hors service')], default='en_service', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprises_vehicules', to='EntrepriseApp.entreprise')),
            ],
        ),
    ]
