# Generated by Django 5.2.17 on 2026-09-29 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffreApp', '0001_initial'),
        ('VehiculeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='Offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offres_vehicules', to='OffreApp.offre'),
        ),
    ]
